version: '3.8'

# Services
services:

    # PHP Service
    php:
        build:
            context: .
            dockerfile: php-dockerfile
        volumes:
            - './php-files:/var/www/html'
            - './composer:/var/www/composer'
        depends_on:
            - mariadb

    # Nginx Service
    nginx:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        links:
            - 'php'
        restart: always
        volumes:
            - './php-files:/var/www/html/:ro'
            - './nginx-conf:/etc/nginx/conf.d/:ro'
            - './certbot/www:/var/www/certbot/:ro'
            - './certbot/conf/:/etc/nginx/ssl/:ro'
        depends_on:
            - php

    # Certbot Service
    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw

    # MariaDB Service
    mariadb:
        image: mariadb:10.9
        environment:
            MYSQL_ROOT_PASSWORD: SecureBD24!
        volumes:
            - mysqldata:/var/lib/mysql

# Volumes
volumes:

    mysqldata:


    #docker compose run --rm  certbot certonly --webroot --webroot-path /var/www/certbot/ -d cookmaster.ovh