<?php
define('COURSES_REQUEST',1);

define('COURSES_PAYED',2);

define('COURSES_ACCEPTED',3);

define('COURSES_REFUSED',4);

define('COURSES_ARCHIVED',5);

define('COURSES_IS_IN_PROGRESS',6);

define('COURSES_IS_ONLINE',0);

define('COURSES_IS_AT_HOME',1);

define('COURSES_ONLINE_PRICE',30);

define('COURSES_AT_HOME_PRICE',200);