<?php 

define('SHIPPING_ADDRESS_NAME_MAX_LENGTH', 75);

define('SHIPPING_ADDRESS_ADDRESS_MAX_LENGTH', 255);

define('SHIPPING_ADDRESS_CITY_MAX_LENGTH', 150);

define('SHIPPING_ADDRESS_COUNTRY_MAX_LENGTH', 150);
