<?php 
//CONST FOR LENGHT OF columns in table subscriptions

//SUBSCRIPTIONS
define('MAX_SUBSCRIPTION_NAME', 40);

define('MIN_SUBSCRIPTION_PRICE', 0);

define('MIN_ACCESS_TO_LESSONS', -1);

define('NO_PAYMENT', 'NO_PAYMENT');

//REWARDS
define('MAX_REWARDS_NAME', 50);

define('MAX_REWARDS_DESCRIPTION', 255);

define('MIN_REWARDS_AMOUNT', 0);

define('REWARDS_CURENCY', array('€','%'));

define('MIN_NB_NEW_SUBSCRIBERS', 0);

//SHIPPING_TYPE
define('MAX_SHIPPING_TYPE_NAME', 100);

//SUBSCRIPTIONS_OPTION
define('MAX_SUBSCRIPTIONS_OPTION_NAME', 150);

define('MAX_SUBSCRIPTIONS_OPTION_DESCRIPTION', 255);

//RENEWAL_BONUS
define('MIN_RENEWAL_BONUS_AMOUNT', 0);

define('RENEWAL_BONUS_CURENCY', array('€', '%'));

define('FREE_SUBSCRIPTION', 'free');
define('STARTER_SUBSCRIPTION', 'starter');
define('MASTER_SUBSCRIPTION', 'master');


?>