name: CookMaster

on:
  push:
    branches: [ "PROD" ]
  pull_request:
    branches: [ "PROD" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: 
      - CookMaster-Runner1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: | 
          echo Hello, world!
          sleep 15
          echo Goodbye!
