name: CookMaster

on:
  push:
    branches: [ "PROD" ]
  pull_request:
    branches: [ "PROD" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: 
      - CookMaster-Runner1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Save the content of the repo in the folder of the docker container /var/www/html
      - name: Copy Files
        run: |
          cp -r /home/cookmaster/lemp/actions-runner/_work/Cook-Master/Cook-Master/Web/* /home/cookmaster/lemp/php-files/
