name: CookMaster

on:
  push:
    branches: [ "PROD" ]
  pull_request:
    branches: [ "PROD" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: 
      - CookMaster-Runner1

    steps:
      - uses: actions/checkout@v2

      - name: Copy Files
        run: |
          cp -r /home/cookmaster/lemp/actions-runner/_work/Cook-Master/Cook-Master/Web/* /home/cookmaster/lemp/php-files/

      - name: Update composer.json
        run: |
          sed -i 's/"require": {[^}]*}/"autoload": { "psr-4": {"App\\": "app/" "Controllers\\": "../Controllers/" "Models\\": "../Models/" "}}/' /home/cookmaster/lemp/php-files/composer.json


