name: CookMaster
on:
  push:
    branches: [ "PROD" ]
  pull_request:
    branches: [ "PROD" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: 
      - CookMaster-Remake

    steps:
      - name: Login to Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - uses: actions/checkout@v2

      - name: Copy Files
        run: |
          cp -r /home/cookmaster/lemp/actions-runner/_work/Cook-Master/Cook-Master/Web/* /home/cookmaster/lemp/php-files/

      - name: Edit composer.json (../WEB)
        run: |
          docker exec lemp-php-1 sed -i 's|../WEB/||g' composer.json

      - name: Edit composer.json (Controllers/)
        run: |
          docker exec lemp-php-1 sed -i 's|Controllers/|controllers/|g' composer.json

      - name: Edit composer.json (Models/)
        run: |
          docker exec lemp-php-1 sed -i 's|Models/|models/|g' composer.json

      - name: Composer Update
        run: |
          docker exec lemp-php-1 composer update
      
      - name: Composer Install
        run: |
          docker exec lemp-php-1 composer install

      - name: Change DEV to PROD
        run: |
          docker exec lemp-php-1 sed -i 's|ENV = DEV|ENV = PROD|g' config/.env
