name: tailscale

on:
  push:
    branches: [ "PROD" ]
  pull_request:
    branches: [ "PROD" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: 
      - CookMaster-Runner1
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Tailscale Action
        uses: ./
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: check for hello.ipn.dev in netmap
        run:
          tailscale status | grep -q hello
