name: CookMaster
on:
  push:
    branches: [ "PROD" ]
  pull_request:
    branches: [ "PROD" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: 
      - CookMaster-Runner1

    steps:

      - uses: actions/checkout@v2

      - name: Copy Web Files
        run: |
          cp -r /home/cookmaster/lemp/actions-runner/_work/Cook-Master/Cook-Master/Api/* /home/cookmaster/lemp/php-files/api/

      - name: Composer Update
        run: |
          docker exec lemp-php-1 bash -c "cd api && composer update"
      
      - name: Composer Install
        run: |
          docker exec lemp-php-1 bash -c "cd api && composer install"
